### ISSUE TITLE
Merge duplicate definitions with testutil

### ISSUE THREAD

**Issue by vidhanarya** [celestiaorg/celestia-app#1073]
Subtask for #832 

Found duplicated function definitions for `generateRandomlySizedTransactions` and `generateRandomlySizedBlobs`
Example ref:
`generateRandomlySizedTransaction(s)`
https://github.com/celestiaorg/celestia-app/blob/8b3dacb24c690fa650a7654f3a5a2f93b44a1c1d/pkg/shares/shares_test.go#L109

https://github.com/celestiaorg/celestia-app/blob/8b3dacb24c690fa650a7654f3a5a2f93b44a1c1d/pkg/shares/shares_test.go#L121

https://github.com/celestiaorg/celestia-app/blob/8b3dacb24c690fa650a7654f3a5a2f93b44a1c1d/pkg/prove/proof_test.go#L189

https://github.com/celestiaorg/celestia-app/blob/8b3dacb24c690fa650a7654f3a5a2f93b44a1c1d/pkg/prove/proof_test.go#L201

Identified Duplicates:
| Duplicates                                                     | Packages         |
|----------------------------------------------------------------|------------------|
| `generateRandomlySizedTransactions`,`generateRandomlySizedTxs` | `shares`,`prove` |
| `generateRandomTransaction`, `generateRandomTxs`               | `shares`,`prove` |
| `generateRandomlySizedBlobs`                                   | `shares`,`prove` |
| `generateRandomBlob`                                           | `shares`,`prove` |
|`GenerateKeyringSigner`, `generateKeyringSigner`, `generateKeyring` | `app`, `app_test`, `testutil`, `x/blob/types` |
|`GenerateManyRawWirePFB`, `GenerateManyRawSendTxs`, `generateRawTx`, `generateManyRawWirePFB`, `generateManyRawSendTxs` | `app`, `app_test`, `blobtestutil` |

Proposal:
- Create a `factory` package inside `testutil` and move all these generators to factory package

**Comment by vidhanarya** [comment]
@evan-forbes @rootulp let me know if this proposal works, have started working on the changes can raise a PR if no concerns.

**Comment by rootulp** [comment]
> Also, couldn't find any epic to link this issue, can someone point me to that if any?

I don't think this falls into an existing epic but we can def answer your other questions without an epic assigned.

> `test_util.go` in the app package collides with the domain of `testutil` package

I get confused by the number of testutil things in this repo. I like your name proposal for a `factory` package that contains `generate*` functions.

> Constant declarations of common variables for testing purposes in individual test files

I don't think there's a ton of value to be gained by consolidating constants used in test files but I'm not against it. For a bit of context, a PR author may create a new constant while writings tests for their PR because they're unaware that another constant may suffice.

I think there is value in consolidating all the `generate*` functions you've done in https://github.com/celestiaorg/celestia-app/issues/1074 because now future PRs shouldn't need to copy + paste this code around for setting up data in tests.

> Not in use?

If not in use, let's delete it 🪓 . CI shouldn't fail if it is needed.
