### ISSUE TITLE
Get multiple message shares from blobs helper

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#1234]
As discussed under https://github.com/celestiaorg/celestia-app/pull/1233/files#r1069423514, we can extend the functionality of:
```
func MsgSharesPosition(tx types.Tx) (beginShare uint64, endShare uint64, err error)
```
to also support transactions containing multiple messages and return their share ranges.

**Comment by evan-forbes** [comment]
to clarify a bit, were referring to sdk.Msgs here afaiu, correct?

**Comment by SweeXordious** [comment]
Now that multiple blobs is merged, I guess we can also support multiple blobs, what do you think?

**Comment by evan-forbes** [comment]
> Now that **multiple blobs** is merged, I guess we can also support **multiple blobs**, what do you think?

not sure what is meant by this mind clarifying, multiple PFBs per tx? that is on the stretch goals yeah

**Comment by rootulp** [comment]
This issue is confusing with respect to the usage of "message". I'm pretty confident it's referring to getting the positions of multiple blobs. Proposal to close this issue in favor of https://github.com/celestiaorg/celestia-app/issues/1315 which conveys the goal a little more clearly. Since this issue is specific to a particular helper function and there's little point to updating the helper to support multiple blobs if we don't have support for share proofs for multiple blobs. Thoughts @SweeXordious ?

**Comment by SweeXordious** [comment]
We can prove multiple blobs if they are in the same namespace. However, for multiple namespaces, it's not supported. Is this what you meant?

**Comment by rootulp** [comment]
> We can prove multiple blobs if they are in the same namespace

I see this is technically possible if a user invoked https://github.com/celestiaorg/celestia-app/blob/150e65de9a6559a64693be88c591d541b2812a8b/pkg/proof/proof.go#L106 with a startShare - endShare that spanned multiple blobs but only one namespace.

> However, for multiple namespaces, it's not supported.

Agreed. Do we need this issue and https://github.com/celestiaorg/celestia-app/issues/1315? I think we can close this in favor of https://github.com/celestiaorg/celestia-app/issues/1315.

**Comment by SweeXordious** [comment]
Yes of course, that one is more general, go for it :+1: Thanks a lot
