### ISSUE TITLE
`merge` doesn't handle PayForBlobNamespaceID

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#1285]
Looks good.

Do we also want to modify the `merge` function in `shares/share_merging.go` to accommodate for the PFB namespace? I think that's the only other place that's missing

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-app/pull/1281#pullrequestreview-1267217197_

**Comment by rootulp** [comment]
`merge` doesn't appear used anywhere outside of `shares_test` and it isn't exported so it seems safe to delete entirely. 

https://github.com/celestiaorg/celestia-app/blob/570dc411d481f05967fbc147f071a316ba687215/pkg/shares/share_merging.go#L14

**Comment by evan-forbes** [comment]
> merge doesn't appear used anywhere outside of shares_test and it isn't exported so it seems safe to delete entirely

I feel like we've discussed this a few times before but haven't dug up our past decisions. IIRC, while its not currently used in core/app, we do want to preserve this functionality because being able to go from the square to block data will be needed in the future, specicically for different types of partial nodes, and we should already have all of the pieces to do that for each reserved namespaces and blobs, so ideally there shouldn't be that much new necessary logic.

While the current roundtrip unit test/fuzzer for merging has not been maintained, it is a very convenient way to fuzz the share encoding. We create random block data, split it, then merge it and compare the input and output for equality.

I can see some reasoning for removing it, but I don't think us not using something now is water tight. If we do want to remove it, then I think we need to write down why we are removing it and in what cases we would add it. Not wanting to maintain the round trip test, or provide any guarantees that we even can do so, until we need the functionality is a perfectly good reason imo. We just need to agree  that is the reasoning, and document that decision.
