### ISSUE TITLE
`docker-security-build` failing 

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#1378]
Currently, when opening a PR, merging to main or creating a tag (didn't try this one), the `docker-security-build` fails with the following:
```
[Invalid workflow file: .github/workflows/docker-build-publish-common.yml#L16](https://github.com/celestiaorg/celestia-app/actions/runs/4166678635/workflow)
The workflow is not valid. .github/workflows/docker-build-publish-common.yml (Line: 16, Col: 3): Error calling workflow 'celestiaorg/.github/.github/workflows/reusable_dockerfile_pipeline.yml@main'. The nested job 'docker-build' is requesting 'contents: write, packages: write', but is only allowed 'contents: read, packages: none'.
```
Which is a permissions' error when starting the job.

**Proposal**:
Update the job to contain the following:
```
jobs:
...
    permissions:
      contents: write
      packages: write
```
So the workflow passes.

Example of a failing run: https://github.com/celestiaorg/celestia-app/actions/runs/4166678635

cc @evan-forbes @MSevey @jrmanes

**Comment by SweeXordious** [comment]
Another fail with the registry name: https://github.com/SweeXordious/celestia-app/actions/runs/4167490248/jobs/7213140197

We might want to use something like this: https://github.com/orgs/community/discussions/27086#discussioncomment-3254548

**Comment by jrmanes** [comment]
> Another fail with the registry name: https://github.com/SweeXordious/celestia-app/actions/runs/4167490248/jobs/7213140197
> 
> We might want to use something like this: https://github.com/orgs/community/discussions/27086#discussioncomment-3254548

I haven't seen this yet, but make sense, if the username contains any capital letter, it will fail...
As this image is not going to be pushed to the registry, it's only a local build, we can tag it with something like:

````
gchr.io/celestiaorg/security-scan:local
````

And we can be sure that it doesn't matter the user name

WDYT?

**Comment by SweeXordious** [comment]
I think that might create problems with PRs created at the same time as 2 PRs will try to push/pull images pushed with the same tag. We can do this if we siffix the image name with some checksum at the end or similar.

Also, if its a PR, then probably it's better to push it to the fork registry instead of the main one as the main registry should only be for images created within the repo (from main branch, tags etc)

What do you think?

**Comment by jrmanes** [comment]
> I think that might create problems with PRs created at the same time as 2 PRs will try to push/pull images pushed with the same tag. We can do this if we siffix the image name with some checksum at the end or similar.
> 
> Also, if its a PR, then probably it's better to push it to the fork registry instead of the main one as the main registry should only be for images created within the repo (from main branch, tags etc)
> 
> What do you think?

I like the idea to tag it with the SHA, but no worries for the push or running 2 PRs at the same time (also, they run in different contexts), we're not pushing this image, it's only being created for using it in the next step for the scan, tho in future, we could even stop the CI if we find any critical bug (which is the ideal world).

Let me show it to you: here is where we build the image, but the `push` is set to false, because we don't want to store it yet:
[here](https://github.com/celestiaorg/.github/blob/main/.github/workflows/reusable_dockerfile_pipeline.yml#L28)

In the next step, [here](https://github.com/celestiaorg/.github/blob/main/.github/workflows/reusable_dockerfile_pipeline.yml#L40) , we are using the image created before.
[Here](https://github.com/celestiaorg/.github/blob/main/.github/workflows/reusable_dockerfile_pipeline.yml#L42) is where we can stop the build in case of any bugs

I can modify the tag to SHA (let me test it first), but no worries for the other :)

**Comment by SweeXordious** [comment]
> but no worries for the other

You mean this:

> Also, if its a PR, then probably it's better to push it to the fork registry instead of the main one as the main registry should only be for images created within the repo (from main branch, tags etc)

?

**Comment by jrmanes** [comment]
> > but no worries for the other
> 
> You mean this:
> 
> > Also, if its a PR, then probably it's better to push it to the fork registry instead of the main one as the main registry should only be for images created within the repo (from main branch, tags etc)
> 
> ?

yes,  we won't push the container during the scan phase

**Comment by SweeXordious** [comment]
makes sense, thanks :+1:
