### ISSUE TITLE
README indicates usage of Go version that we don't support

### ISSUE THREAD

**Issue by smuu** [celestiaorg/celestia-app#1470]
### Summary of Bug

The README indicates you can build the application with Go version 1.18 or higher. See [here](https://github.com/celestiaorg/celestia-app/blob/main/README.md?plain=1#L35).

From #769, #1328, and other PRs, only 1.18 is supported, and later versions could cause bugs.

### Version

In the README, we should clarify which Go version(s) are supported and which not to avoid bugs that are hard to debug and could create frustration on the user side.

### Steps to Reproduce

-

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Hmm good point. We assume that Go 1.18+ will work for compiling/installing celestia-app but we currently don't test with any other Go versions. Instead of claiming Go 1.18+ support, I think the README should explicitly state the version it supports (1.18). In the future, we can expand that to a range if/when we introduce a matrix test that verifies celestia-app compiled with Go 1.18/1.19/1.20 behave as expected.
