### ISSUE TITLE
Remove or unexport the DefaultMinSquareSize

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1636]
I would extend this question to ask more generally, what would be the benefit of choosing a `DefaultMinSquareSize` greater than 1?

_Originally posted by @cmwaters in https://github.com/celestiaorg/celestia-app/pull/1604#discussion_r1169919583_

I can't think of any reason we would want to. I believe this was a remnant of malleation, where we might want to eventually decrease the number of sizes that users would have to sign over if the square size got enormous. We do still use it to calculate force a square size of 1 on an empty block, which is something we want, so while we might not be able to remove, we could unexport it.

**Comment by rootulp** [comment]
Note this is related to https://github.com/celestiaorg/celestia-app/issues/1517 because celestia-node currently imports this constant [here](https://github.com/rootulp/celestia-node/blob/ed417840608e75d0d94c45249e6b8186c3d7d481/share/empty.go#L25) which means we can't unexport it from celestia-app without modifying the logic in celestia-node.

Why do we want to unexport it? My impression is that there still is a minimum square size but it is no longer a default because it can't be modified by parameter. We may consider renaming `DefaultMinSquareSize` to `MinSquareSize` but keeping it exported.

**Comment by cmwaters** [comment]
I would have thought we would have simply removed that parameter (and so would celestia-node). Logically, the smallest square is 1 (or 0 🤔 )

**Comment by rootulp** [comment]
> simply removed that parameter 

Note, [DefaultMinSquareSize](https://github.com/celestiaorg/celestia-app/blob/3767e3eb35230eb50e44c7c2f8b49ed3701d346b/pkg/appconsts/appconsts.go#L68-L69) is a constant and not a parameter. There were previously square size parameters for the `x/blob` module but those were removed in https://github.com/celestiaorg/celestia-app/pull/1567

**Comment by cmwaters** [comment]
Sorry by parameter, I meant constant.

**Comment by rootulp** [comment]
Seems closed b/c `DefaultMinSquareSize` no longer exists in celestia-app or go-square
