### ISSUE TITLE
Add new templates for the spec

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#1818]
During our internal audit, we will revamping the existing specs and still need to decide on the structure we want. In order to document that structure and remain consistent, we should create templates. 

For example, in the section that describes all of the block validity rules, we could have something along the lines of

```markdown
# Rule N: <name of rule>
<specifiy the exact block validity rule so that ... >

## Mechanism of Enforcement
<is there a fraud proof for this rule? if not, are there plans to include a fraud proof in the future? if so, what does that fraud proof look like?>

## Consequences of the rule being broken
```

or for modules we have 

```markdown
# x/<name

## Abstract
<hight level overview of what the module  does>

## State
<what state if any is being read, updated, written, deleted etc>

## Events
...
```

the end result can look very different from the above, just so long as we have a rough idea over what should be expected for different sections of the specs. This might also mean coming up a new way to organize the specs.

**Comment by staheri14** [comment]
Regarding the document template, I suggest the following structure (also added a brief description of what should be contained under each section):

## Abstract
Provide a concise description of the purpose of the component for which the specification is written, along with its contribution to the celestial-app or other relevant parts of the system. Make sure to include proper references to the relevant sections.

## Protocol/Component Description
Offer a comprehensive explanation of the protocol, covering aspects such as data flow, communication mechanisms, and any other details necessary for understanding the inner workings of this component.

## Message Structure/Communication Format 
If this particular component is expected to communicate over the network, outline the structure of the message protocol, including details such as field interpretation, message format, and any other relevant information.

## Assumptions and Considerations 
If there are any assumptions required for the component's correct operation, performance, security, or other expected features, outline them here. Additionally, provide any relevant considerations related to security or other concerns.

## Implementation
Include a link to the location where the implementation of this protocol can be found. Note that specific implementation details should be documented in the core-app repository rather than in the specification document.

## References
List any references used or cited in the document.

**Comment by staheri14** [comment]
In my suggested template,  what @evan-forbes has proposed for the block validity rule part, will go under the **Protocol/Component Description** i.e.,


# Protocol/Component Description
## Rule N: <name of rule>
<specifiy the exact block validity rule so that ... >
### Mechanism of Enforcement
<is there a fraud proof for this rule? if not, are there plans to include a fraud proof in the future? if so, what does that fraud proof look like?>
### Consequences of the rule being broken

**Comment by staheri14** [comment]
We can consider implementing the [COSS model](https://github.com/unprotocols/rfc/blob/master/2/README.md) for our specification process. In this model, our specifications would be overseen by main editor(s) and potentially involve contributors. The specifications would be associated with a defined [state and lifecycle](https://github.com/unprotocols/rfc/blob/master/2/README.md#coss-lifecycle), as well as the use of appropriate [language](https://github.com/unprotocols/rfc/blob/master/2/README.md#language) to emphasize the essential elements of the design.

**Comment by rootulp** [comment]
Agreed w/ the proposed templates. How do we plan on decomposing the app into components that implement the spec template? In other words, how do we break https://github.com/celestiaorg/celestia-app/tree/main/app down into components? I think there can be a one to one mapping of spec for modules in https://github.com/celestiaorg/celestia-app/tree/main/x

**Comment by staheri14** [comment]
>  I think there can be a one to one mapping of spec for modules in https://github.com/celestiaorg/celestia-app/tree/main/x

Certainly, that would be the case. Additionally, block construction warrants a distinct specification separate from the process proposal and preparation of the proposal. We can actually discuss these components in our upcoming call.

**Comment by staheri14** [comment]
It would also be beneficial to collect links to all our available specifications (just where they collectively reside e.g., the core-app go repo, etc.), both for reference purposes and to utilize existing content in order to expedite the spec writing process. cc: @evan-forbes
