### ISSUE TITLE
Support gas refunds

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#1944]
Currently when a user estimates the amount of gas required for their transaction, if they underestimate, their transaction is not executed but they still pay the gas, if they overestimate they pay more than what was necessary. Striking this balance is difficult but doesn't need to be. We can simply refund any remaining fee back to the user so they can safely overestimate and only pay for what they use.

For the implementation this would mean defining a post antehandler which is run after the transaction

**Comment by rootulp** [comment]
Rough steps:

1. Test the existing behavior: https://github.com/celestiaorg/celestia-app/pull/2885
2. Draft a prototype of fee refunds based on gas consumption
3. Write a CIP
4. Polish prototype and get it ready to merge

**Comment by rootulp** [comment]
During a discussion w/ @evan-forbes it became clear that "gas refunds" may not be the best way to describe this line of work to users. It's not clear why user's would receive a "gas refund". Also current name collides with the Cosmos SDK method [`RefundGas`](https://github.com/cosmos/cosmos-sdk/blob/6bea474d3ac99c61b14b50b047ee356b7f38b6ef/store/gas.go#L71-L73) which actually isn't needed for this.

Since all of the tx fee is deducted from the fee payer via the ante handler, we're exploring adding a posthandler that refunds the fee payer a portion of the tx fee that is based on the gas consumption of the tx. As a result, tx fees experienced by users are gas consumption-based rather than always the entire fee.

As a result, we could describe the entire fee system after this change as: gas consumption based tx fees. The portion we're adding to the posthandler could be described as gas consumption based tx fee refunds.

**Comment by rootulp** [comment]
>  if they underestimate, their transaction is not executed but they still pay the gas

Hmm I can't repro this behavior. See this [pastebin](https://pastebin.com/tEnCWJZ3)

**Comment by rootulp** [comment]
We put this line of work on pause b/c the mitigation strategies [here](https://github.com/celestiaorg/CIPs/blob/3243f1916110737c4f707038c4ec38f0bf24981e/cips/cip-11.md?plain=1#L63-L66) were deemed too complicated.
