### ISSUE TITLE
Remove the `Minter` struct from genesis

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#2067]
## Context

https://github.com/celestiaorg/celestia-app/blob/60f932802e30c31c2f9dfa810bce0e74902cf716/x/mint/keeper/genesis.go#L8-L16

## Problem

Currently, the minter struct is exposed in the genesis file:

```json
    "mint": {
      "minter": {
        "inflation_rate": "0.080000000000000000",
        "annual_provisions": "0.000000000000000000",
        "previous_block_time": null,
        "bond_denom": "utia"
      }
    },
```

None of these fields is not used in the app:

- `inflation_rate`: Even if a value is set at this level, the inflation rates are hard-coded and these values are not used:
https://github.com/celestiaorg/celestia-app/blob/60f932802e30c31c2f9dfa810bce0e74902cf716/x/mint/abci.go#L29

- `annual_provisions`: Also calculated in `BeginBlocker` in the first block:
https://github.com/celestiaorg/celestia-app/blob/60f932802e30c31c2f9dfa810bce0e74902cf716/x/mint/abci.go#L42

- `previous_block_time`: Already not specified in genesis
- `bond_denom`: This parameter is not expected to change at all

## Proposal

Remove the `Minter` struct from genesis. 

We could also remove the protobuf definition (To be confirmed) as the `Minter` struct will only be stored in state, and not written to genesis, or used in tx/queries

**Comment by rootulp** [comment]
I think we should preserve `bond_denom` in the genesis for consistency with other modules (i.e. x/staking [here](https://github.com/celestiaorg/networks/blob/bf13b34c7b671297d2b90385369639c4253bcf11/arabica-9/genesis.json#L61131), x/gov [here](https://github.com/celestiaorg/networks/blob/bf13b34c7b671297d2b90385369639c4253bcf11/arabica-9/genesis.json#L61052)). I agree, the other fields should be removed from the genesis file because they are overwritten at block one anyway. Unfortunately, I think this may be a breaking change that is too late to include in the v1.0.0 release because it implies a change to the genesis.json.

**Comment by SweeXordious** [comment]
I agree, but concerning this:
```
Unfortunately, I think this may be a breaking change that is too late to include in the v1.0.0 release because it implies a change to the genesis.json.
```
Even if we remove those fields from the struct, or even remove the whole `Minter` struct, the app won't complain if fed a genesis file containing those fields. So we can keep the same genesis while having this issue implemented
