### ISSUE TITLE
docker/doc: Document Dockerfile and Dockerfile.ephemeral in the docker/README.md

### ISSUE THREAD

**Issue by Bidon15** [celestiaorg/celestia-app#2118]
Yes. Ideally, we need to make a dedicated issue to document other 2 DockerFiles we have in the repo. 
I started this ReadMe, so we can spec out not only the protocol, but what options do we have to run the software apart from vanilla `make install && celestia-appd xyz` in the host machine

_Originally posted by @Bidon15 in https://github.com/celestiaorg/celestia-app/pull/2052#discussion_r1266626496_

**Comment by evan-forbes** [comment]
I think we can delete the docker.ephemeral, correct? that was just for the ephemeral cluster iirc

**Comment by rootulp** [comment]
> I think we can delete the docker.ephemeral, correct? that was just for the ephemeral cluster iirc

Context in https://github.com/celestiaorg/celestia-app/pull/415 . Since https://github.com/celestiaorg/ephemeral-cluster is in archive mode, it may no longer be used in which case I agree we should remove [Dockerfile_ephemeral](https://github.com/celestiaorg/celestia-app/blob/main/docker/Dockerfile_ephemeral)

**Comment by evan-forbes** [comment]
can we close this issue?

**Comment by rootulp** [comment]
Looks like there's another Dockerfile (`Dockerfile.test`) that we should document or remove. I plan on removing.
