### ISSUE TITLE
review: future proof appconsts SubtreeRootThreshold

### ISSUE THREAD

**Issue by tuxcanfly** [celestiaorg/celestia-app#2158]
> We should future proof these methods. 

```suggestion
func SubtreeRootThreshold(version uint64) int {
        switch version {
        case v1.Version:
              return v1.SubtreeRootThreshold
        default:
             panic('invalid version for SubtreeRootThreshold')
        }
}
```

> also doesn't hurt to have a unit test for these.

_Originally posted by @MSevey in https://github.com/rollkit/celestia-openrpc/pull/32#discussion_r1269589211_

**Comment by rootulp** [comment]
Note, there is an [existing thread](https://github.com/celestiaorg/celestia-app/pull/1768#discussion_r1196780507) that discusses the pros and cons of a switch statement with a default `panic`.

**Comment by evan-forbes** [comment]
per that thread, adding pacnics doesn't actually provide us with anything since comet is already checking during header verification. this means that in the application these can never get hit in the event that a chain updates and a consensus node is not aware of that upgrade.

there is almost all downside for core/app because if we forget to update a value, for example one that only gets hit once a year (like if we make a consensus breaking change to the mint module), then we will panic, halting the chain simply because we forgot to update or test a value.

similarly, other repos that import these values **must** do the same thing, where they check that the app version changed how they expected it to during header verification anyway. If they are doing that, then the same concept applies and they only open up a potential halt if there is a human error

**Comment by evan-forbes** [comment]
if that makes sense @tuxcanfly and @MSevey then I think we can close this issue

**Comment by MSevey** [comment]
fine to close
