### ISSUE TITLE
Investigate why the CI is failing for the docker builds

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#2249]
The docker builds are failing in https://github.com/celestiaorg/celestia-app/actions/runs/5826402602/job/15800294504 and https://github.com/celestiaorg/celestia-app/actions/runs/5826402602/job/15800295465 in this https://github.com/celestiaorg/celestia-app/commit/b7899da29277007f49a7a5b38014273505f61265, we need to investigate why

**Comment by rootulp** [comment]
Specifically the docker-security step of both workflows: docker-security-build and docker-txsim-build.

I think we should consider renaming the workflow docker-security-build to something like docker-celestia-appd because IIUC there are two Docker workflows: one for the celestia-appd binary and one for tx-sim binary

**Comment by mojtaba-esk** [comment]
`sudo make build-docker`
This might give a clue: https://git.musl-libc.org/cgit/musl/tree/include/sys/poll.h

**Comment by SweeXordious** [comment]
> `sudo make build-docker` This might give a clue: https://git.musl-libc.org/cgit/musl/tree/include/sys/poll.h

That's a separate thing, I will create a separate issue to handle that warning
