### ISSUE TITLE
Mint module: AppModule Updates

### ISSUE THREAD

**Issue by onurakpolat** [celestiaorg/celestia-app#2502]
## Mint module

| ID             | 006                                                                                        |
|----------------|--------------------------------------------------------------------------------------------|
| Finding        | AppModule Updates                                                                           |
| Severity       | 0 - Informational                                                                          |
| Description    | There are a few interface method implementations that could use re-evaluation. Specifically: The legacy querier is deprecated and newer chains should avoid implementing functionality that is now deprecated (see: LegacyQuerierHandler). Double check that all types and interfaces are registered in RegisterInterfaces. |
| Recommendation | See description.                                                                           |
| Code References| x/mint/module.go                                                                           |

**Comment by rootulp** [comment]
>  The legacy querier is deprecated and newer chains should avoid implementing functionality that is now deprecated (see: LegacyQuerierHandler).

is resolved because we removed the legacy querier in https://github.com/celestiaorg/celestia-app/pull/2258

> Double check that all types and interfaces are registered in RegisterInterfaces.

Since the x/mint module doesn't define any new interface types, I don't think any types needs to be registered. Do you mind clarifying if you think a type should be registered? It's currently a no-op [here](https://github.com/celestiaorg/celestia-app/blob/58c1e4ed41d8bba734f808a3f8dfd3b53cc9a535/x/mint/module.go#L44-L45).

@onurakpolat can you please comment?
