### ISSUE TITLE
Make distinct go modules for the `/pkg` directory and celestia-app modules in `/x`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2570]
In order to help downstream teams avoid dependency hell, we should begin using go modules for some of our packages similar to what most rust projects do.

We should at least do this for the `/pkg` and `/x` directories, but could go further by including a go.mod in each subdirectory of `/x`.

ref https://github.com/celestiaorg/rsmt2d/issues/248 + a bunch of issues in node and rollkit

**Comment by rootulp** [comment]
Note: this should be easier to do for `pkg/shares` because https://github.com/celestiaorg/celestia-app/pull/2659 merged.

**Comment by rootulp** [comment]
This seems close-able because we extracted https://github.com/celestiaorg/go-square . Note: go-square doesn't include the `/x` modules stated in the OP but I think those are less useful for downstream apps compared to the `/pkg` modules. Please re-open or open a new issue if you feel differently @cmwaters @evan-forbes
