### ISSUE TITLE
Rename the state machine QGB variables

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/celestia-app#2586]
Currently, the `qgb` name/prefix is used thoroughly inside the state machine:

- The store keys:
https://github.com/celestiaorg/celestia-app/blob/daed1a58cbf40e28a05ced63481853aec7bc7a2c/x/qgb/types/keys.go#L10-L23

- The proto packages:
https://github.com/celestiaorg/celestia-app/blob/daed1a58cbf40e28a05ced63481853aec7bc7a2c/proto/celestia/qgb/v1/genesis.proto#L2-L5
and others.

- The query routes:
https://github.com/celestiaorg/celestia-app/blob/daed1a58cbf40e28a05ced63481853aec7bc7a2c/proto/celestia/qgb/v1/query.proto#L15-L69

- The transaction route:
https://github.com/celestiaorg/celestia-app/blob/daed1a58cbf40e28a05ced63481853aec7bc7a2c/proto/celestia/qgb/v1/tx.proto#L17-L20

Which would require a hardfork if we want to rename. 

## Proposal

Rename the `qgb` related fields to `bridge`, `gateway`, `portal` or something generic so that it sticks everywhere.

cc @evan-forbes @adlerjohn

**Comment by evan-forbes** [comment]
good idea to just name it something generic, lets do this as soon as possible. this will also require a hardspoon I think, so we might actually have to wait for v2 to rename things 

if that's the case then we should also have the infrastructure in place to upgrade/migrate as well

**Comment by SweeXordious** [comment]
if we do it before mainnet launch, then we won't hardspoon ever, I think. And the QGB prefixes can always stay generic, it's okey, no?

**Comment by evan-forbes** [comment]
if the transaction type change due to the proto name change, that will require a hardspoon since we want to remain backwards compatible, and nodes that sync will have to be able to handle both transaction types

plus it looks like the store key changes, no?

wfyt about internally refering to all things qgb as "the relay"?

**Comment by SweeXordious** [comment]
> if the transaction type change due to the proto name change, that will require a hardspoon since we want to remain backwards compatible, and nodes that sync will have to be able to handle both transaction types

That's true, but did anyone ever send a register address tx on mocha? I suspect that since we didn't ask them to activate the QGB. That's why I think it's okey not to care.

> plus it looks like the store key changes, no?
 
yes, for mocha. we will need to hardfork. I was refering to mainnet when I said that we don't need to hardfork it.

> wfyt about internally refering to all things qgb as "the relay"?

sounds good to me. We can use `relay` internally, and keep the QGB in the comments and docs until we find a new name

**Comment by evan-forbes** [comment]
per our sync discussion: we will have to hardspoon mocha assuming we want to stay backwards compatible, as there are important keys and the name of the txs (we can't renaming a proto type without being consensus breaking)

**Comment by SweeXordious** [comment]
I'll start then renaming using the `relay` prefix. How does that sound?

**Comment by RandyPen** [comment]
emm

**Comment by rach-id** [comment]
no longer needed as we're switching to BlobstreamX
