### ISSUE TITLE
bug: fix makefile to correctly indicate correct solution for missing `gcc` package

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/celestia-app#2597]
Generated from [a discord thread](https://discord.com/channels/638338779505229824/804370245778276374/1157366838326476890):

## Problem

> FYI: The suggestion here doesn't actually work:
>> gcc not installed for ledger support, please install or set LEDGER_ENABLED=false.  Stop.

This is for building celestia-app. @MicahZoltu found that they were "able to install GCC and get around it, but the error message was a lie when it said I could do `LEDGER_ENABLED=false` to avoid needing GCC."

**Comment by rootulp** [comment]
Matt cleaned up [this section](https://github.com/celestiaorg/celestia-app/blob/9791d9528a9edae1627aea0ae038d381042f056d/Makefile#L11-L34) of the Makefile on main but it hasn't been backported to v1.x. I verified by checking that "gcc not installed" does not appear on [main](https://github.com/celestiaorg/celestia-app/blob/44e8165cb37ccb4924cfd405493a67b6a2d7caa0/Makefile) so in order to close this issue, we likely want to backport https://github.com/celestiaorg/celestia-app/pull/2449

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/celestia-app/pull/2612
