### ISSUE TITLE
Investigate gas cost of a byte in the IBC memo field

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2687]
## Context

IBC messages may contain a [memo](https://github.com/cosmos/ibc-go/blob/830982adfb4448573f8898bbd07a73d06bff640a/docs/docs/02-apps/01-transfer/04-messages.md?plain=1#L42).

## Proposal

Investigate the gas cost of a byte in the IBC memo field and compare it to the gas cost of a byte in a PFB blob.

**Comment by evan-forbes** [comment]
one simple and accurate way of doing this is compare the entire gas costs of the txs sumibtted to mocha and comparing it to a similarly large pfb tx. 

some potential outcomes of this:

1. wait until IBC fixes the issue (as I believe its consensus breaking)
2. price tx bytes even higher
3. price blob bytes lower

The major downside of people including data in ibc transactions instead of PFBs is that consensus nodes have to download all of that data in the future

**Comment by rootulp** [comment]
On first glance, I don't see why a byte in the IBC memo field would be priced any differently than via `auth.TxSizeCostPerByte=10`. It's also worth noting that it doesn't look like there is an explicit bound on the max IBC memo.

> Chains should ensure that there is some length limit on the entire packet data to ensure that the packet does not become a DOS vector.

[Source](https://github.com/cosmos/ibc/blob/2c661b986f92ccee3ebc05e560b2e8b8ba96f30e/spec/app/ics-020-fungible-token-transfer/README.md?plain=1#L340C440-L340C574)

**Comment by rootulp** [comment]
Quick comparison:
1. PFB [tx](https://www.mintscan.io/celestia/tx/dc52745e2bc3530137d4c7b3758781ddc592b994766cefb0b845f59092bec899/?height=562949) with 109,383 byte blob used 990,636 gas. 
1. IBC [tx](https://www.mintscan.io/celestia/tx/284598E05B93DB254EFB5CBAA146E8F5FEC914A33CD99DCA5105076BE55D07FA?height=558188) with 963 byte memo used 105,786 gas.

but that doesn't seem informative enough so I'm going to analyze gas costs on a local devnet.

**Comment by rootulp** [comment]
Confirmed that characters in the IBC memo field are charged based on via `auth.TxSizeCostPerByte=10`. See [this test](https://github.com/celestiaorg/celestia-app/commit/a612fd6eb54b6f45da7a9b20827e1006a216257d#diff-b18d1347df122ce477542856aad9aaf0a360f87aceb76131359e20c9676e6b5eR202-R204).
