### ISSUE TITLE
Goreleaser pre-built binaries don't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#2727]
When ran locally on two different distributions of linux we hit

```
./celestia-appd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./celestia-appd)
./celestia-appd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./celestia-appd)
./celestia-appd: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./celestia-appd)
```

**Comment by evan-forbes** [comment]
from the internet

```
Ubuntu 20.04 has glibc 2.31.

Binaries compiled on operating systems which have a newer glibc are linked to the newer version (in this case 2.32-2.34), and won't work on systems with an older glibc.

You gotta compile the app on an older OS, or if possible statically link it by using the x86_64-unknown-linux-musl target.
```

**Comment by rootulp** [comment]
> on two different distributions of linux

Which distributions of Linux caused this error? Asking so we know how to verify the fix.

**Comment by rootulp** [comment]
I think we'll need to test specific Linux versions because when I tested https://github.com/celestiaorg/celestia-app/pull/2654 with the defaults on Digital Ocean and AWS celestia-appd worked.

<img width="462" alt="Screenshot 2023-10-19 at 6 31 27 PM" src="https://github.com/celestiaorg/celestia-app/assets/3699047/2420f281-db76-4713-a5d7-e613f52c512a">
