### ISSUE TITLE
Set DiscardABCIResponses to true by default

### ISSUE THREAD

**Issue by cmwaters** [celestiaorg/celestia-app#2746]
### Summary

This will reduce the amount of data persisted in state.db

### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by rootulp** [comment]
Do we deem this "breaking"? Based on the [docs](https://docs.celestia.org/nodes/consensus-node/#optional-discard-abci-responses-configuration) I'm considering a scenario where a node operator who runs a public RPC endpoint upgrades to a release with the default set to `true`. Will this break queries for `/block_results`?

**Comment by evan-forbes** [comment]
I don't consider this breaking since its only a default configuration change. If they upgrade their node, their config is not touched and they will not see a difference. I could see this being unexpected if they have a deployment script however.

in general, I think we can have better docs by explaining the consequences of each change, listing the defaults, and demonstrating how to change them via the cli and a bash script

**Comment by cmwaters** [comment]
I second evans comments.

We do already have this mentioned in the docs btw: https://docs.celestia.org/nodes/consensus-node/#optional-discard-abci-responses-configuration

**Comment by rootulp** [comment]
> If they upgrade their node, their config is not touched and they will not see a difference.

Good point. I don't think we should mark it "breaking" then.

**Comment by cmwaters** [comment]
Can we close this @rootulp?

**Comment by rootulp** [comment]
Yes it appears to have been closed by https://github.com/celestiaorg/celestia-app/pull/2764
