### ISSUE TITLE
feat(download-genesis): support new chain-ids

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#2792]
## Context

We're adding a `download-genesis [chain-id]` command in https://github.com/celestiaorg/celestia-app/pull/2791 that only supports hard-coded chain-ids: `celestia`, `mocha-4`, `arabica-10`.

## Problem

When new testnets get spun up, we'll need a code change in celestia-app to support them. The code change needs to add the chain-id to the list of known chain-ids, and add a sha-256 hash of the genesis file for that testnet.

## Proposal

Investigate a solution that doesn't need hard-coded sha-256 hashes + chain-ids.

**Comment by evan-forbes** [comment]
just my two cents, but I think its fine to only support this feature for long lived networks by manually adding the hashes since other networks can use the normal mechanism of just manually downloading the genesis.

I feel like the diff of curling something vs modifying a config or flag to curl something in a command is really small. We should however document that people can submit PRs to include any long lived networks in the binary.

**Comment by rootulp** [comment]
Agreed. Based on that it seems like we can close this issue via documenting how to add a new chain-id to the download genesis command.
