### ISSUE TITLE
`PrepareProposal` always passes v0 to `GovSquareSizeUpperBound`

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#3066]
Unlike `ProcessProposal`, when `PreparePropsoal` creates a [sdk context](https://github.com/celestiaorg/celestia-app/blob/ef3c0d574973fb8aabedb1c1d9626f6a24ccdb31/app/prepare_proposal.go#L25-L29) it's not setting the version in the header. This becomes an issue when calling`GovMaxSquareSize`, which uses the app version found in the header.

https://github.com/celestiaorg/celestia-app/blob/ef3c0d574973fb8aabedb1c1d9626f6a24ccdb31/app/square_size.go#L22

When the version changes, v0 will still be used for `GovMaxSquareSize`. To fix this, `GovSquareSizeUpperBound` should always use the paramstore/baseapp app version.

**Comment by rootulp** [comment]
I'm preemptively re-opening this issue based on the revert in https://github.com/celestiaorg/celestia-app/pull/3089

I think we need unit tests for square_size.go that tests the behavior of this function given different contexts (i.e. what happens if app version is 0, 1, 2. What happens when the block version is 0, 1, 2)
