### ISSUE TITLE
Make constants version specific in specs

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3191]
[tangent] we don't have to figure this out in this PR but I wonder if it would make sense to include the app version that a constant is applicable for in this table. For example, I think some of these params could be modified to be different in different app versions and at that point it's not immediately obvious if this table should reflect the original or updated value. Perhaps both with a new column for app version?

_Originally posted by @rootulp in https://github.com/celestiaorg/celestia-app/pull/3094#discussion_r1530503420_

**Comment by staheri14** [comment]
Documenting the value of a versioned constant for each applicable app version makes sense to me.

PS: if a constant becomes dependent on the app version, it likely needs to remain versioned indefinitely, making all future app versions applicable. So, considering this, the value of the constant needs to be recorded for _all_ app versions, but _not_ a _subset_ of them.

**Comment by rootulp** [comment]
On second thought, I don't think this issue is strictly necessary.

If we want to differentiate versioned parameters, one idea is: 
1. Add a new table to https://celestiaorg.github.io/celestia-app/specs/params.html for **Versioned Parameters**
1. Add versioned params (`SquareSizeUpperBound`, `SubtreeRootThreshold` ) into that new table

I don't think we should move `minfee.GlobalMinGasPrice` from the existing **Module Parameters** table to the **VersionedParameters** table because it's governance modifiable and specific to the minfee module.
