### ISSUE TITLE
Potential bug preventing app from syncing from scratch 

### ISSUE THREAD

**Issue by ninabarbakadze** [celestiaorg/celestia-app#3284]
## Description

while investigating #3167 and going through historical commits using git bisect it output the first commit that supposedly broke syncing a52ed2612d9070af7133dd1c8b3a519d1b9eefaa introduced by this pr https://github.com/celestiaorg/celestia-app/pull/2583

**Comment by cmwaters** [comment]
I'm going to start working on this. My hunch is that the app hash mismatch is caused by the fact that `main` doesn't have an `upgrade` module in it's v1 yet `v1.x` has. This is because the `upgrade` module was extended to include the signalling component for coordination. My plan is to actually separate these out into two modules: an `x/upgrade` which just includes the ibc stuff and should look the same as v1, and `x/signal` for coordinating upgrades
