### ISSUE TITLE
Consensus node crashes with "too many concurrent timer firings"

### ISSUE THREAD

**Issue by kernelpanic9** [celestiaorg/celestia-app#4018]
### Summary of Bug

Observed several consecutive crashes with the error `too many concurrent timer firings`.
Attaching crash dump.
[celestia_crash_20241030.log](https://github.com/user-attachments/files/17579881/celestia_crash_20241030.log)

### Version

2.3.0-mocha

### Steps to Reproduce

Node crashes while syncing or following tip.

**Comment by evan-forbes** [comment]
hey @kernelpanic9, thanks for bringing this in! do you mind posting the relevant logs in a gist so that I don't have to download a random file?

I've never hit this error before, and unfortunately it appears to be a standard golang error instead of a comet/core specific error. This makes it difficult to determine where this error is comming from.

which version of block sync are you using in the config? have you tried state sync?

**Comment by Sebby83** [comment]
Hi @evan-forbes,
Logs pasted to: https://gist.github.com/Sebby83/4f5563e1fdf87f1b57358eafb72e00d5
Its happening quite frequently on our instance: 51 times during 8 days.

sync settings from config.toml: 
```
[statesync]
enable = false
rpc_servers = ""
trust_height = 0
trust_hash = ""
trust_period = "168h0m0s"
discovery_time = "15s"
temp_dir = ""
chunk_request_timeout = "10s"
chunk_fetchers = "4"

[fastsync]
version = "v0"
```

**Comment by Sebby83** [comment]
Thanks for a prompt reply. 
Due to Celesia Bridge node requirements, I upgraded celestia-app to 3.0.2 and moved it to different server.  So far no crash observed.

I'll keep an eye on it and I'll let you know when another crash happens.

**Comment by rootulp** [comment]
Thanks for the update! Will close for now, please re-open if it repros.
