### ISSUE TITLE
API Node Returns incomplete Block Data

### ISSUE THREAD

**Issue by freedombird9** [celestiaorg/celestia-app#4057]
After upgarding to celestia-app v3.0.1, query query /cosmos/tx/v1beta1/txs?events=tx.height=2876500&page=1&limit=100 only returns the first transaction: 84D8A4D3A6461BA7D57B0A3214C16C4F268ABA2F902C85124A928A7B5CE812D1

The other 7 transactions are not returned. We're following https://github.com/celestiaorg/celestia-app/releases/tag/v3.0.1 to upgrade our node. The public API node does return the correct data.

**Comment by mindstyle85** [comment]
hmm. i think issues still arent fixed @evan-forbes , ive also seen another report on discord

**Comment by rootulp** [comment]
Thanks for opening the issue @freedombird9 and reporting @mindstyle85 . This issue looks like https://github.com/celestiaorg/celestia-core/issues/1526 which was fixed by https://github.com/celestiaorg/celestia-core/pull/1533 but it hasn't been released. I just cut celestia-core https://github.com/celestiaorg/celestia-core/releases/tag/v1.44.0-tm-v0.34.35 and bumped to it in https://github.com/celestiaorg/celestia-app/pull/4059.

@freedombird9 can you confirm this PR fixes your issue? If you tell me which platform and architecture you're on, I can generate a binary for you. Alternatively, you can checkout the code on https://github.com/celestiaorg/celestia-app/pull/4059, generate the binary (via `make build` or `make install`) and then re-run your node and the query.

**Comment by mindstyle85** [comment]
oh i see, i thought this was fixed in 3.0.1 hence why i pinged so fast

**Comment by rootulp** [comment]
We'll try to release it in v3.0.2 ASAP.

**Comment by rootulp** [comment]
Released v3.0.2: https://github.com/celestiaorg/celestia-app/releases/tag/v3.0.2
