### ISSUE TITLE
Adjust share size to match the spec and add namespaces to each Message

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#53]
Namespaces are now kept in the actual message to ensure that they are recoverable, see [the spec PR](https://github.com/lazyledger/lazyledger-specs/pull/146/files). This should also be accounted for in the app, specifically `SHARE_SIZE - NAMESPACE_ID_BYTES - SHARE_RESERVED_BYTES`

**Comment by adlerjohn** [comment]
To clarify:
1. the share size that is erasure coded is still `SHARE_SIZE`
2. `SHARE_SIZE - NAMESPACE_ID_BYTES - SHARE_RESERVED_BYTES` is how requests with a reserved namespace ID are chunked (txs, intermediate state roots, evidence)
3. SHARE_SIZE - NAMESPACE_ID_BYTES` is how messages are chunked

**Comment by evan-forbes** [comment]
Yeah, that should definitely be clarified.

When [generating the commitments](https://github.com/lazyledger/lazyledger-app/blob/d09e631e73328b7e3c9d5d748301350c0fe15bc6/x/lazyledgerapp/types/payformessage.go#L254) for `SignedTransactionDataPayForMessage`, namespaces are not added to each share after chunking the message. This is what specifically needs to be fixed.

The (WIP) ll-core PR [#235](https://github.com/lazyledger/lazyledger-core/pull/235) is using a const [AdjustedMessageSize](https://github.com/lazyledger/lazyledger-core/blob/1ff8b305986e04ee3df247014e355dc8682290a5/types/consts.go#L21), and I think the app should import this.

**Comment by liamsi** [comment]
There is also something else to consider here: the spec currently assumes SHARE_RESERVED_BYTES to be one byte. That almost works because it is an index. "almost" because if the index is > 127, its encoding currently will actually be 2 bytes long: https://play.golang.org/p/C_wN1E-lKRY 

Also, note that indpendent of the above issue, the current implementation does not use this index but rather length prefixed all messages (see https://github.com/lazyledger/lazyledger-core/issues/234)

**Comment by adlerjohn** [comment]
So...in my head canon I assumed it would just be 1 byte, but you're correct the canonical serialization is prescribed

> (the `*` in the example layout figure below) is the starting byte of the length of the canonically serialized first request that starts in the share, or `0` if there is none, as a canonically serialized big-endian unsigned integer

Now we have a problem: if we use canonical protobuf, this could be 1 or 2 bytes.
1. We can't always use 2 bytes because that's invalid canonical protobuf.
1. We don't really want to use a variable number of bytes because it makes the chunking logic more complex...but we could.

**Comment by liamsi** [comment]
> We could just not use canonical protobuf and instead just use the uint8 byte directly.

I think this will be our best choice.

**Comment by adlerjohn** [comment]
Yes, the length can be varint encoded because it doesn't affect chunking logic.

**Comment by liamsi** [comment]
Can this be closed?

**Comment by adlerjohn** [comment]
I'm not sure, I asked about this during the off-site and didn't get a conclusive answer on whether it was implemented. cc @evan-forbes

**Comment by evan-forbes** [comment]
Sorry, I should have been clearer. The commitments that are generated do include the namespace of the message, but they do not add the length delimiter.

We also need more testing to compare the generated commitments with the subtree roots of an actual square, to make sure that we are doing this important step correctly in the future. This would also help test [#49](https://github.com/celestiaorg/nmt/pull/49)

https://github.com/celestiaorg/celestia-app/blob/1fcccc414127b1dd8399ad35051c8f669a98aa56/x/payment/types/payformessage.go#L140-L147

**Comment by evan-forbes** [comment]
Was thinking about his more, and while we could use code from core that already exists 
https://github.com/celestiaorg/celestia-app/blob/ad49814f62879319d60d722beb237bbdc21ba9fa/x/payment/types/payformessage.go#L111-L127

we could also move the commitment creation code to celestia-core, that way it would easier to roundtrip test

**Comment by evan-forbes** [comment]
I don't think we need this any longer, and am unsure of the context
