### ISSUE TITLE
slim down abci app

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/celestia-app#57]
Before launch, we should further strip down the state machine to a bare minimum that supports staking, fees, and transfers fees only. That said, governance and upgrades might also be part of this. 

Action items:
 - [ ] narrow down which modules are the bare minimum and document why they are required in the specs
 - [ ] remove/disable all other module and delete any unused code

**Comment by liamsi** [comment]
I think this issue is bit too vague/outdated. We surely should go through each module again before launch and document the rationale for its inclusion (or drop it if feasible). I'll update the opening comment.

**Comment by evan-forbes** [comment]
I went through all of the modules, and the only remaining one that we don't technically need is the `feegranter` module ([spec](https://github.com/celestiaorg/cosmos-sdk/blob/release/v0.46.x-celestia/x/feegrant/spec/README.md)). We do not have a planned use case for this atm, but it might be useful since it would allow arbitrary parties to set aside funds explicitly for the gas fees of other keys.

**Comment by liamsi** [comment]
Yes, I think it is small yet useful enough to keep it. We should do an internal detailed review of the module (like any other we are including).
