### ISSUE TITLE
Require `MsgWirePayForData` and `MsgPayForData` txs to sign over all relevant square sizes to be considered valid

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#620]
Currently, someone can easily modify the code to not sign over any square sizes, or only sign over a single square size. Transaction with only a single singed square size will tend to get stuck in mempools, and txs with no signed over square sizes _will_ get stuck in the mempool. 

To prevent this, we could add a check to the `ValidateBasic` methods to ensure that all relevant shares are signed over. This will ensure that `WirePayForData` transactions do not get stuck in mempools.

more info in relevant square sizes can be found in #236

**Comment by rootulp** [comment]
I agree that these transactions need to sign over at least one message square to be considered valid. However it seems possible for there to be only one valid square size that a user signs over when the message they send can only fit in the largest possible square `k=128` (based on [specs](https://celestiaorg.github.io/celestia-specs/latest/specs/networking.html?highlight=Wire#wiretxpayformessage) and [this line](https://github.com/celestiaorg/celestia-core/blob/3c6122ae98f3ea98d4885a986d3e8d5ec1077d45/pkg/consts/consts.go#L34)). Therefore, it's not clear to me how we should handle the case where only one square size is signed over. I don't think we should throw an error from `ValidateBasic()` for this scenario because it's valid but unlikely.

**Comment by adlerjohn** [comment]
There being only one valid configuration isn't contradictory to "we could add a check to the ValidateBasic methods to ensure that all relevant shares are signed over."

**Comment by rootulp** [comment]
> we could add a check to the ValidateBasic methods to ensure that all relevant shares are signed over.

Sorry I don't understand what check needs to be added. Is this not sufficient? https://github.com/celestiaorg/celestia-app/blob/1fe223b7558aa01f7f7797bcd5bfdbe2125e9dcb/x/payment/types/wirepayfordata.go#L105-L119

**Comment by evan-forbes** [comment]
from #236 

> This does not account for the fact that commitments do not change if the message can fit on a single row. Meaning that if a message can fit on a single row of square size x, then a valid commitment for square size x is valid for all square sizes >= x.

so ideally we would have a function that determines all of the possible square sizes to sign over, not unlike https://github.com/celestiaorg/celestia-app/blob/ff2d92a98584b5f3f0fef0bdf595e21fdd808a97/x/payment/types/square_sizes.go#L24-L41

the more important part would be to modify `PrepareProposal` to be aware of this and select for a commitment even if the commitment doesn't match the square size perfectly

**Comment by rootulp** [comment]
Thanks for clarifying @adlerjohn @evan-forbes ! I understand now and think https://github.com/celestiaorg/celestia-app/pull/666 should resolve this issue.
