### ISSUE TITLE
Test compatibility of SplitMessages with/without share index

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/celestia-app#632]
### Context
During non-interactive defaults, we added empty message shares that act as padding between messages. In order for transactions to be linked to the share(s) that they pay for, `indexes` were added to [SplitMessages](https://github.com/celestiaorg/celestia-app/blob/a3ef48c582403f6df13d1a65635c5fadbdbfbd3f/pkg/shares/split.go#L96). 

### Problem Definition

Since `indexes` didn't exist in v0.6.0, we need to verify if v0.6.0 is compatible with main.

Ref:
- https://github.com/celestiaorg/celestia-app/blob/a3ef48c582403f6df13d1a65635c5fadbdbfbd3f/pkg/shares/split.go#L69
- https://github.com/celestiaorg/celestia-app/blob/a3ef48c582403f6df13d1a65635c5fadbdbfbd3f/pkg/shares/split.go#L96

### Proposal

Write a unit test or integ test that verifies compatibility of `SplitMessages` with/without share index

**Comment by evan-forbes** [comment]
to expand on this slightly, the current tests do test comparability of the encoding and decoding, as we haven't changed them in #627 and won't be changing them when introducing non-interactive defaults either. 

What we need to add is a mechanism to detect that we are decoding an old block, so that we don't add any padding or care if there is a share index in the wrapped transactions. This could be as simple (and implicit) as reading the first share index from a wrapped transaction. If that index is 0, then we automatically know that we are reading an old block, and can pass `nil` to `SplitMessages(nil, msgs)`, which effectively uses identical share splitting code to v0.6.0

**Comment by evan-forbes** [comment]
ref #608
