### ISSUE TITLE
Update the tx inclusion proving code to follow the non-interactive defaults

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#703]
in #702 we're moving the tx inclusion code to the app, from which we can query it from core as part of #698. We will also have to update that code so that it follows the non-interactive defaults.

**Comment by evan-forbes** [comment]
related to #956

**Comment by SweeXordious** [comment]
Any more details on this? Which parts of the tx inclusion doesn't support NID?
I think they're independent of that, since for the transaction, which don't follow NID, we go over the transactions to get the index. Then, from the transaction, we get the start index of the message. 
Let me know what I am missing please

**Comment by evan-forbes** [comment]
there could be a message in the same row as the txs, which depends on NIDs, and is needed to create proofs to the txs. 

ideally we don't regenerate the entire square each time, but if that makes it easier then I say we do it and optimize later. 

one easy optimization is to encode the entire block data into shares, but then only erasure the relevant rows when creating proofs

**Comment by SweeXordious** [comment]
> ideally we don't regenerate the entire square each time, but if that makes it easier then I say we do it and optimize later.

In a tx inclusion proof, we receive the block data already generated from core, why regenerate?

**Comment by rootulp** [comment]
Closing in favor of https://github.com/celestiaorg/celestia-app/issues/1243
