### ISSUE TITLE
Consider treating namespaced padding as blobs or sequences

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#783]
With the non-interactive defaults, we introduced padding between messages. Per the original specs [`Caveats`](https://github.com/celestiaorg/celestia-specs/blob/e59efd63a2165866584833e91e1cb8a6ed8c8203/src/rationale/message_block_layout.md#caveats) section of Message Layout Rational, these are described as 

> [Namespaced padded shares] have a value of zero and a namespace ID equal to the preceding message's. Since their value is known, they can be omitted from NMT proofs of all shares of a given namespace ID.

We should consider updating the implementation and specs to treat the each section of padding as individual messages. This will prepend an info byte along with a length delimiter.

edit: ~~While the added bytes would break the second property,~~
> Since their value is known, they can be omitted from NMT proofs of all shares of a given namespace ID.

this might mean that light clients could skip these shares entirely when parsing a namespace.

**Comment by musalbas** [comment]
Afaik this would only break the second property for the first padding share, as it has different message lengths.

**Comment by rootulp** [comment]
> this might mean that light clients could skip these shares entirely when parsing a namespace.

In order for this to be the case, additional metadata must be added to the share so that a client can differentiate between a sequence of namespaced padding shares and a sequence of shares with `0` data. See https://github.com/celestiaorg/celestia-app/issues/1136

**Comment by musalbas** [comment]
Assuming that all padding shares have a start indicator of 1, and data len of 0, then shouldn't you be able to differentiate padding shares from non-padding shares, because only padding shares can have a start indicator of 1 and data len of 0?

**Comment by rootulp** [comment]
Good point. celestia-app denies blob sizes of `0` [here](https://github.com/celestiaorg/celestia-app/blob/0b447adf776689cc8f14823c6ef925b8f8249b5a/x/blob/types/payforblob.go#L208-L210) so it is possible to treat a share with a sequence start indicator of `1` and a sequence length of `0` as a namespaced padding share. 

Pros:
- an additional reserved bit is not needed

Cons: 
- prevents us from writing a sequence length for the number of padding bytes that follow to the first namespaced padded share. I briefly considered that option so that clients could read the first namespaced padded share and learn how many padding shares followed and potentially skip downloading them. An alternative optimization with similar benefit may  be possible because a namespaced padded share has a variable namespace id and constant contents.

**Comment by musalbas** [comment]
>prevents us from writing a sequence length for the number of padding bytes that follow to the first namespaced padded share. I briefly considered that option so that clients could read the first namespaced padded share and learn how many padding shares followed and potentially skip downloading them. An alternative optimization with similar benefit may be possible because a namespaced padded share has a variable namespace id and constant contents.

I think they can learn that using the method described in: https://github.com/celestiaorg/celestia-app/issues/1136#issuecomment-1401615109 (cc @adlerjohn)

>Consider a model where a full storage node does not send padding shares to a rollup light node over the wire, but simply tells them "hey, shares between index x to y are padding, and here's the sub-tree root of those shares". The light node can then recompute the sub-tree root of those padding shares itself, to authenticate that statement.
