### ISSUE TITLE
Consolidate utility testing functions where possible

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-app#832]
As we've discussed synchronously many times, there's quite a bit of redundant testing utility functions. We should consolidate where possible. If its not possible due to cyclic imports, then we should consider putting those tests in their own package. 

related to #829

**Comment by amoghrajesh** [comment]
@evan-forbes I can work on this issue. Can you point me to the files to get started?

**Comment by rootulp** [comment]
A candidate sub-task for this issue is to delete the duplicate definitions of `randomValidNamespace`:
1. https://github.com/celestiaorg/celestia-app/blob/27632ddc804fbf7655ef5ba941eb4f346c539be9/testutil/payment/testutil.go#L134
2. https://github.com/celestiaorg/celestia-app/blob/e18de882c3de4ee92e4632af21d4007c1b642adb/app/test_util.go#L178
3. https://github.com/celestiaorg/celestia-app/blob/8f4fd811b19b8539bfd9e77e83f23518ec702c88/app/test/block_size_test.go#L299
4. https://github.com/celestiaorg/celestia-app/blob/906fdf74f871f13d3fe0c632dfda95db494521ee/pkg/prove/proof_test.go#L290
5. https://github.com/celestiaorg/celestia-app/blob/07b5bb4a6dd905166c33b3434895cd292501f100/testutil/utils.go#L15

The last function definition is the most preferred because it accounts for the parity and tail padding namespaces. Note: the duplicate functions are defined in different packages so the last function may need to be extracted to a package that can be imported by all usages of the duplicate definitions.

**Comment by rootulp** [comment]
Spun out https://github.com/celestiaorg/celestia-app/issues/836 in-case @evan-forbes has other ideas for what this issue should include.

**Comment by evan-forbes** [comment]
another instance per this https://github.com/celestiaorg/celestia-app/pull/1991#discussion_r1243461687

**Comment by rootulp** [comment]
Closing this b/c it's not actionable. Please re-open or create a new issue with more specific examples of the redundant testing utilities that need consolidation.
