### ISSUE TITLE
Start mocked QGB testnet 

### ISSUE THREAD

**Issue by SweeXordious** [celestiaorg/celestia-app#953]
Starting a QGB V1 testnet that can be exposed to developers to start tinkering with the QGB.
Currently, QGB V1 is at `qgb-integration` branch. And, we're working on a mocked version using a mocked validator set to be able to run it for any test network without the need to make everyone run an orchestrator.

Some of the tasks that will need to be accomplished for this are:

- [ ] https://github.com/celestiaorg/celestia-app/issues/1375
- [ ] https://github.com/celestiaorg/quantum-gravity-bridge/issues/136

**Comment by evan-forbes** [comment]
instead of starting a full blown testnet for v1, we should be able to deploy the QGB contracts using a mock validator set. This would entail creating a validator set of one that never changes, then querying data commitments for arbitrary block ranges, signing them, and manually relaying them to the contracts. 

This way, we would be able to use the block data from mocha and arabica, so users of the QGB could just post data to those networks, this script would create data commitments over that block data, and post it to the contracts using the mocked validator set.

**Comment by SweeXordious** [comment]
A potential approach, since mocha and arabica have the QGB state machine plugged in, would be to make changes on QGB V1 to do the following:

- Get the attestations from the state machine (this part is already implemented).

- Sign the attestation using 1 validator key: if the attestation is a valset, update its content to contain only the key and the power of the validator signing instead of the whole validator set.

- send that attesation to the relayer to be submitted: this would require making the following changes:
    - Merge the QGB CLI config of the orchestrator and the relayer
    - Start the Relayer when starting the orchestrator
    - update the relayer not to get the confirms from the state machine but get them as a parameter (or it might be easier to just listen on a channel. This channel will contain the signatures pushed by the orchestrator after the orchestrator signs an attestation).
   
- Remove the use of queries that are not supported in V2: checking the main branch QGB queries and only use the ones defined there.

**Comment by evan-forbes** [comment]
is this still planned @SweeXordious ?

**Comment by SweeXordious** [comment]
I don' think we need this anymore, we've done the above tasks using v2 on Robusta. Should we should be good to close this. Thanks for pointing it.
