### ISSUE TITLE
Allow force triggering CI using commit message flags

### ISSUE THREAD

**Issue by rahulghangas** [celestiaorg/celestia-app#994]
### Summary

Currently there's no way to trigger CI if there is no diff in go source or dependency files

### Proposal

Add ability to trigger CI using flags in commit messages. Since we squash merge PRs, including such flags do not add clutter to commit history

**Comment by rahulghangas** [comment]
@evan-forbes @rootulp @SweeXordious @MSevey thoughts?

**Comment by rootulp** [comment]
Can you please describe a situation where this is desired? Is re-running a CI job to temporarily workaround flaky tests insufficient? A failed CI job can be re-triggered via

<img width="261" alt="Screenshot 2022-11-10 at 2 36 43 PM" src="https://user-images.githubusercontent.com/3699047/201189930-00db3794-7e02-4064-b9ec-7ff0ad17e8cf.png">

**Comment by rahulghangas** [comment]
Particularly useful when changing actions file or configuring the build

**Comment by SweeXordious** [comment]
> if there is no diff in go source or dependency files

I think that if no source files were changed, then, no need to run CI.  But, I don't have an opinion really, flags might be useful in other scenarios too

**Comment by MSevey** [comment]
I'm not really following the use case. 

> configuring the build

If we need to trigger the CI manually, i.e. a release, we have the `workflow_dispatch` trigger already enabled on the CI. So if there are other CI elements that need to be manually triggered for some reason, we can use that.

`workflow_dispatch` seems much easier than commit message flags, but that could just be because that is what I'm used to. 

> Particularly useful when changing actions file

I'm not following this. What action file changes are you doing that don't trigger a run? If you are doing something related to issues for example, and what to test it to ensure it is working, I think it is easier to just test it on a local repo and get it working and then submit a PR here.

**Comment by rahulghangas** [comment]
Test and covergae report generation don't get triggered on actions file changes because the diff on go source files and `mod` and `sum` files remains the same. Specifically, #966 . Then I remembered I've previously dealt with this by allowing runs via commit message flags, something like `chore: change sed command --force-build`

**Comment by MSevey** [comment]
That sounds like a CI trigger misalignment then.

It is easy to have the CI always run on pull requests if the trigger is `pull_requests`

If the problem is our filtering of the action execution then that should be addressed. Neither requires triggering via commit messages. 

for #966 for example, that entire workflow is trigger on `workflow_call`, which is currently being called from the CI_Release action for certain push events, all pull_request events, and workflow_dispatch events. 

So if there is a specific case that we are not running the CI when we think we should, I think we should first ensure the CI triggers are set up accordingly and that and custom file filtering for specific actions is validated. 

Forcing things via commit messages feels like a work around for some other bug imo

**Comment by rootulp** [comment]
@rahulghangas do we still want this?

**Comment by rahulghangas** [comment]
No, I circumvented it for the time being. Since we haven't reached consensus on this, I'm closing this
